### ISSUE TITLE
Ponavljanje koda

### ISSUE THREAD

**Issue by josip-volarevic** [nikola-zitko/IT---C-Structures-and-algorithms#8]
```
int n = SMALLER(n1, n2);
int* presjekNiza = (int*)malloc(n * sizeof(int));
```

U vježbi 3 se te dvi linije koda ponavljaju tri puta. Trebalo bi napraviti neku funkciju koja će to odrađivati.

**Comment by nikola-zitko** [comment]
Zasto ne samo stavit mozda `int* presjekNiza = (int*)malloc(SMALLER(n1, n2) * sizeof(int));`
Tribalo bi radit i skrati liniju odnosno tri koda. Funkcija bi bila kompliciranje.

**Comment by josip-volarevic** [comment]
A trebalo bi spremiti vrijednost od SMALLER(n1, n2) negdje jer se kasnije opet koristi. Funkcija bi bila nepotrebno kompliciranje tako da ću jednostavno zatvoriti ovaj problem i ostaviti ovako
