### ISSUE TITLE
Skratit kod #2

### ISSUE THREAD

**Issue by josip-volarevic** [nikola-zitko/IT---C-Structures-and-algorithms#9]
Kod se ponavlja na više mjesta, ako je moguće napravit neku funkciju ili nešto slično što bi učinilo taj kod ponovno iskoristivim na više mjesta (_reusable code_)
```
clock_t start_t, end_t, total_t;
start_t = clock();
```

```
end_t = clock();
total_t = (int)(end_t - start_t) / CLOCKS_PER_SEC;
printf("Ukupno vrijeme u sekundama: %d\n", total_t);
```

**Comment by nikola-zitko** [comment]
Nisan bas siguran da se moze u funkciju jer bit ovog koda je racunanje vremena izmedu pocetka i kraja. Mozda i moze al ja bi ostavia ovako.

**Comment by josip-volarevic** [comment]
Istina, nepotrebno kompliciranje i zahtjeva znanje koje nemamo

**Comment by josip-volarevic** [comment]
Mjerenje vremena izvođenja funkcije sortiranja
```
double measure(void(*sort)(int *niz, int n), int *niz, int n) {
	int start_time = clock();
	sort(niz, n);
	int end_time = clock();
	return (double)(end_time - start_time) / CLOCKS_PER_SEC;
}
```

Funkcija ipak nije primjenjiva na ovaj zadatak jer je mrvicu kompleksnije od ovoga. Ne isplati se sada trošiti vrijeme na to.

Isto se može i skratiti koja linija na optimiziranju duplikacije fje presjek_sortiran( ) i presjek_sortiran_qsort( )
